blank_issues_enabled: true
contact_links:
  - name: 📚 Nuxt Vitalizer Documentation
    url: https://github.com/johannschopplich/nuxt-vitalizer
    about: Check the documentation for usage of Nuxt Vitalizer
